author: Bayrock
description: "Inside a shallow mind"
avatar: /assets/img/lain.gif
favicon: false
#email: bayrock@example.com
repository: bayrock/bayrock.github.io
show_downloads: false
#google_analytics: ""
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-coffeescript

sidebar:
  - name: GitHub
    icon: fa-brands fa-github
    link:
      href: https://github.com/bayrock
      new-tab: true
  - name: Portfolio
    icon: fa-solid fa-mug-hot
    link: 
      href: /jekyll-portfolio/portfolio
  - name: Blog
    icon: fa-solid fa-pen
    link: 
      href: /jekyll-portfolio/blog

portfolio:
  - name: Devinity
    homepage: https://devinity.org
    description: Home of the classic Garry's Mod Flood gamemode and community
  - name: Entropia Analyst
    homepage: https://bayrock.github.io/Entropia-Analyst/
    repo: bayrock/Entropia-Analyst
    description: Web based visualization of Entropia Universe skill gains
  - name: OSRS Gadget
    homepage: https://bayrock.github.io/OSRS-Gadget/
    repo: bayrock/OSRS-Tools
    description: Web based tools and calculators for Old School Runescape
